### ISSUE TITLE
3DR Services "Learn More" link is dead

### ISSUE THREAD

**Issue by squilter** [DroidPlanner/DroneKit-Android#139] opened 2015-05-15 20:28 UTC
Clicking the "learn more" button links to [here](https://droidplanner.github.io/3DRServices/)

**Comment by mrpollo** [comment] 2015-05-15 20:52
@squilter where is the learn more link?

**Comment by squilter** [comment] 2015-05-15 23:31
![screenshot_2015-05-15-19-27-32](https://cloud.githubusercontent.com/assets/2956460/7663481/f4095ec0-fb38-11e4-97bf-1621dfc07326.png)

Upper right corner.

**Comment by hamishwillee** [comment] 2015-05-18 01:06
Definitely a defect - points to non-existent doc set https://droidplanner.github.io/ . 

The problem is that it isn't clear where this should go. This is a learn-more from within the app, so I'd expect it to link to an end-user rather than developer page. We could send to the [Google play page](https://play.google.com/store/apps/details?id=org.droidplanner.services.android&hl=en) but the user will already have seen that as they have already downloaded the app. 

We could perhaps link to the [Github page for services](https://github.com/DroidPlanner/DroneKit-Android/tree/master/ServiceApp) but it is not really appropriate for end users. The [dronekit docs](http://android.dronekit.io/getting_started.html#installing-3dr-services-on-your-mobile-device) also not particularly useful for end users.

@ne0fhyk @mrpollo My response would be to point them back to the google play page for the services. If not that, Fredia, what was the intent of the link?

**Comment by ne0fhyk** [comment] 2015-05-18 20:36
@hamishwillee Since the app is mostly exposed through Tower at the moment, the intent was to lead them to the developer page as Tower's audience is (mostly) advanced.
 
That's about to shift with the upcoming solo launch however, as the bulk of the audience will be beginner and/or intermediate drone users. However I still think we can should point them to the main `DroneKit` landing page to 'educate' them about `DroneKit`, the platform powering the app they're using.

**Comment by hamishwillee** [comment] 2015-05-19 00:33
@ne0fhyk Makes sense! Fixed by #140

**Comment by ne0fhyk** [comment] 2015-05-19 01:34
Cool! It's been merged in.

**Closed by ne0fhyk** 2015-05-19 01:34 UTC
Labels: bug
